name: build-and-push

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/setup-buildx-action@v2
  
    - name: Kaniko build
      uses: aevea/action-kaniko@v0.10.0
      with:
        image: garacio/csgo-server
        tag: ${{ github.run_id }}
        registry: ghcr.io
        username: garacio
        password: ${{ secrets.GITHUB_TOKEN }}

